### ISSUE TITLE
Exception on runtime

### ISSUE THREAD

**Issue by RosalesJ** [yurikhan/kitty-grab#2]
## Issue
Immediately after triggering the hotkey the following exception occurs:
```
Exception in callback Loop._read_ready(<kitten.GrabH...t 0x10ae3eeb8>, 6)
Traceback (most recent call last):
  File "Python/events.py", line 88, in _run
  File "kitty/loop.py", line 188, in _read_ready
  File "kitty/loop.py", line 265, in _on_apc
  File "/Users/coby/.config/kitty/grab2.py", line 273, in on_key
    action = self.shortcut_action(key_event)
  File "kitty/handler.py", line 37, in shortcut_action
AttributeError: 'GrabHandler' object has no attribute '_key_shortcuts'

Press the Enter key to quit
```

The only version of kitty I've tested this on is 0.13.2, but I haven't been able to get it to work in 0.13.0.

**Comment by yurikhan** [comment]
I reproduced it both on 0.13.0 and 0.13.2. It happens when you *do* have a config file `grab.conf` in your configuration directory, but it *does not* map any keys. I think I fixed it now, please test.

**Comment by RosalesJ** [comment]
Thank you, this looks like it fixes the crash. Tested that it also works in 0.13.3. Maybe the default ```grab.conf``` should uncomment the default commands, it was still a little confusing as to why nothing was happening when I tried to move the cursor.

Anyways for all intents and purposes this is fixed.

**Comment by yurikhan** [comment]
I think it is convention to show defaults in a configuration file but keep them commented. The problem was that defaults were not merged correctly with the values read from the file. Now they should, so even with an empty config (e.g. all lines commented out) you should have the default keys.
